### ISSUE TITLE
Move All Convars To a Single File

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#12]
Something trigger did on Super Siege, was have every convar in the code be on a single 'convars.lua' doc, and have the convars in the code reference this doc. It made it easier to find and tweak values.

**Comment by TheRealNin** [comment]
console variables? such as?

**Comment by DalinSeivewright** [comment]
I believe he means all of the global k-prefixed variables.  Not sure it's of value here as the coders will presumably be working in an IDE where they can grep the code.

**Comment by jonsextra** [comment]
[I believe this was it. ](https://github.com/TimeSkwanderer/SuperSiegeMod-Beta/blob/master/lua/Additions/Convars.lua) Just a single file with all the values that we might have to tweak for balance reasons in the same place.

**Comment by TheRealNin** [comment]
That's horrible. Please can we just override the values we want to tweak like here? https://github.com/TheRealNin/SiegeBalance/blob/master/source/lua/SiegeBalance/Balance.lua

**Comment by jonsextra** [comment]
If that's easier than do that. To me this just seemed like the easiest way to keep track of everything and to make values easy to find in the future.

**Comment by TheRealNin** [comment]
Wouldn't it be easier to just check if a value has been modified by looking at the lua, and see if it's there? We aren't going to be changing dozens of variables, are we?

**Comment by jonsextra** [comment]
I hope not, but you never know. You do what you think is the best option, this affects the coders not the game. I had just suggested it because it seemed like it would make things easier.

**Comment by TheRealNin** [comment]
We are going to keep the balance changes in a small project, and only overwrite the variables we need. If someone wants to check to see what is being changed, it's pretty quick to just open the files and check instead of having to audit an entire 3000 line file and compare it to NS2.
