### ISSUE TITLE
Add two channel to phasegate (like simplesiege)

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#23]
PASSED with a vote of 5/2/2 (y/n/a)

**Comment by TheRealNin** [comment]
Gonna need more info on this

**Comment by DalinSeivewright** [comment]
Other siege had a phase gate system where you could have two separate networks of PG.  Phase gate A would go A-> B > C > A while phase gate D would go D > E > F > G.  Think two separate linked lists i guess.  The comm chose which pg was in which network i believe, like a toggle switch.  But i dont know much more than that.  I never bothered changing channels as comm in siege simple.

**Comment by DalinSeivewright** [comment]
Implemented as a separate mod, "Two Channel Phase Gates"  Workshop:  http://steamcommunity.com/sharedfiles/filedetails/?id=1109912658

It seems to work without issue so far so closing this now.
