### ISSUE TITLE
Add mapstats command but make it admin only

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#24]
PASSED with a vote of 7/0/0 (y/n/a)

**Comment by TheRealNin** [comment]
I'll need to know where we can get this command, or what it does

**Comment by jonsextra** [comment]
I don't know where the command came from, it may have been written from scratch, but we could always use [Wonitor](https://github.com/eBrute/wonitor).

**Comment by jonsextra** [comment]
Shoot, looking at the data Wonitor provides that might be a good idea to do anyway. Would there be a way to make it so that only admins can see it?

**Comment by TheRealNin** [comment]
Why bother? Why not make it public info?

**Comment by jonsextra** [comment]
Like Death said, no need for the plebs to know, they'll just complain no matter what they do. On top of that, if they see that they're on a team that appears to be heavily disadvantaged on a map they might leave.

**Comment by TheRealNin** [comment]
Now solved by Wonitor
