### ISSUE TITLE
Simple's Shine Commands

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#3]
PASSED with a vote of 7/0/0 (y/n/a).
We need the shine commands that we had on Simple. Hell, we could also use the immunity levels / usergroups that it had as well. It was nice being able to designate people as regulars.

**Comment by TheRealNin** [comment]
Could we get a detailed list of what commands you want and what they do?

**Comment by jonsextra** [comment]
Keep in mind that many of these that appear to only be for abuse are useful for testing.

sh_randomrr : Randomises the ready room

sh_motd : Message of the day, brings up the steam group.

sh_give [player] [entity] [team] : Gives the target player an entity (armory, hive, shotgun, egg, etc) that is on the designated team (1 = Marines 2 = Aliens)

sh_destroy [string] : Destroys all of an entity within a radius (8 radius)

sh_stalemate : Ends the current round with the "draw game" screen

sh_chat "TEXT" : Chat that only mods can see

sh_pm [player] "TEXT" : Message that only the target player can see.

sh_respawn [player] : Respawns the target player

sh_addbotcomm : Enables bot commanders w/o a vote.

sh_forceroundstart : Forces the round to start

sh_open [string] : Opens the front/primary/siege door

sh_phealth [player] [number] : Sets the target player's health to X

sh_parmor [player] [number] : Sets the target player's armor to X

sh_sethealth [string] [number]:  Sets all target entities health within a radius (8 radius) to X

sh_setarmor [string] [number]:  Sets all target entities armor within a radius (8 radius) to X

sh_giveres  [player] [amount] : Gives the target player X pres

sh_setres  [player] [amount] : Sets the target player to X pres

sh_addscore [player] [amount] : Gives the target player X score

sh_setscore [player] [amount] : Sets the target player to X score

sh_slap [player] [time] : Teleports a player in a random direction once per second for X seconds

sh_bury [player] [time] : Teleports a player 1/2 M down, then at the conclusion of X seconds, teleports a player 1/2M up

**Comment by Frozenclaw** [comment]
Do we need all these commands? We seem to be doing fine with the current commands.

**Comment by jonsextra** [comment]
Yes we need these commands. They're extremely useful and make testing, damage control, and administration significantly easier.

**Comment by Frozenclaw** [comment]
Doesn't default shine have half these commands?

**Comment by jonsextra** [comment]
Not unless they don't appear when I run sh_help.

**Comment by Frozenclaw** [comment]
sh_randomrr : Randomises the ready room -- Already exists as !randomize @rr 

sh_motd : Message of the day, brings up the steam group. -- Already Exists just have to edit.

sh_give [player] [entity] [team] : Gives the target player an entity (armory, hive, shotgun, egg, etc) that is on the designated team (1 = Marines 2 = Aliens) --- Why do we want an alien to have a marine weapon/vice versa.

sh_stalemate : Ends the current round with the "draw game" screen -- I believe this already exists


These are needed for testing?

sh_slap [player] [time] : Teleports a player in a random direction once per second for X seconds

sh_bury [player] [time] : Teleports a player 1/2 M down, then at the conclusion of X seconds, teleports a player 1/2M up

sh_babbler [player] : Turns the player into a babbler for the duration of their current life.

sh_respawn [player] : Respawns the target player

The rest i'll Look into but it really seems like a bunch of useless commands to me. I see maybe 4 that would be useful.

**Comment by jonsextra** [comment]
sh_randomrr would be a command that we could give to lower privileged moderators. They need to be able to randomize the ready room, but they don't necessarily need to be able to force random.

sh_motd exists, yes you're correct. 

sh_give is massively useful for testing. Being able to check damage is extremely helpful, and specifying the team can be useful for MvM. 

sh_stalemate isn't a command I've ever seen available. 

sh_respawn is useful for testing, especially when you have limited test subjects. 

The other commands are useful for administration purposes. They give admins a harmless way to mess around.

I've justified this command list several times before this. Every command on this list was something I used regularly back on simple, and I keep finding myself needing them for various purposes.

**Comment by Frozenclaw** [comment]
So "sh_babbler [player] : Turns the player into a babbler for the duration of their current life." is in because....?????

**Comment by jonsextra** [comment]
Somebody suggested it, a lot of people liked it, and Nin said it was possible.

**Comment by TheRealNin** [comment]
Seems pretty useless!

**Comment by jonsextra** [comment]
It's useful in that it gives admins a silly way to mess around on the server. Can you imagine a massive babbler deathmatch?

**Comment by TheRealNin** [comment]
I can also imagine the amount of work it would take ;)

**Comment by jonsextra** [comment]
Alright, talked to Katzenfleisch about the viability of sh_babbler in the hopes we could cannibalize code from the Faded mod. Said that what he had done was gone through and replaced every individual aspect of skulks (model, animations, taunts, etc.) with that of babblers. Also said that it'd all have to be rewritten in order to be usable, and that it'd be a full day's work for someone who knows what they're doing. The idea of this command is massively popular on the server, but between the amount of effort it'd take and the fact that it's not one of simple's command, I'm going to pull it from this list and put it in a separate bill. Posting this so that the previous comment chain has context. 

Addendum: He did say that he'd be working on making it a shine plugin, but that it'd be a ways out.

**Comment by jonsextra** [comment]
Repealed by issue #84 with a vote of 7/1/0 (y/n/a).
