### ISSUE TITLE
 Revert Contamination cooldown to 60 seconds, but give it 3 charges

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#31]
PASSED with a vote of 6/0/1 (y/n/a)

**Comment by TheRealNin** [comment]
First part is done - I also extended the "lifetime" of the contamination to 60 seconds, so it'll stick around long enough to make your eggs/buildings useful

**Comment by jonsextra** [comment]
Issue amended to "Revert Contamination cooldown to 60 seconds, and increase its lifetime to 60 sec" by a vote of 8/0/0 (y/n/a). As this has already been implemented, the issue will be closed.
