### ISSUE TITLE
Make closed gorge-tunnels invisible on the map and minimap

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#33]
PASSED with a vote of 7/0/0 (y/n/a)

**Comment by DalinSeivewright** [comment]
Initial feature for this is in.  Minor issue with it though logged here:  https://github.com/DalinSeivewright/HideableGorgeTunnels/issues/1

Leaving this open until that is fixed.

**Comment by DalinSeivewright** [comment]
Closing this.  The feature seems to work ATM.
One minor bug exists but I don't think it affects gameplay too much.
