### ISSUE TITLE
Make fade's vertical acceleration the same as its horizontal acceleration, reduce blink's energy cost by 10%

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#39]
PASSED with a vote of 7/3/0 (y/n/a)

**Comment by TheRealNin** [comment]
Acceleration is already the same.

**Comment by cryticx** [comment]
I suggest closing this, as the change referred to was in fact the old method of Fade blink that allowed turning horizontal velocity into vertical velocity.

**Comment by jonsextra** [comment]
I'd still say that reducing fade's blink energy cost is a good idea.

**Comment by cryticx** [comment]
Alright.

**Comment by TheRealNin** [comment]
Hellllllll to the no. And I play a lot of fade. They're already very very good.

**Comment by TheRealNin** [comment]
Perhaps we should reconsider this after the increase of alien HP

**Comment by cryticx** [comment]
Well the bill already passed for that, so...

**Comment by jonsextra** [comment]
We can remove the bill with another vote.

**Comment by TheRealNin** [comment]
We can't implement the old bill as it was written anyways

**Comment by DalinSeivewright** [comment]
Bill it up please.  I have been playing Fade more lately and am quite happy with it atm.

**Comment by jonsextra** [comment]
Done

**Comment by TheRealNin** [comment]
Jon just put the bill up :)

**Comment by jonsextra** [comment]
Issue closed by vote. PASSED with a vote of 6/0/0 (y/n/a)
