### ISSUE TITLE
Pressing K as a commander makes you lose your cursor

### ISSUE THREAD

**Issue by TheRealNin** [TheRealNin/Siege-Collection#42]

**Comment by GregariousJB** [comment]
The new K key window is really cool-looking, but unfortunately not very practical - you won't be able to fit all the server's changes into it.

Maybe have the "major" changes in the K key window, but I'd recommend looking into an ESC key window, like on Luckyfkers' server: ![image](http://i.imgur.com/emmTDHd.jpg)

It's a scrollable window, so you have plenty of space. You could even do a changelog of some kind so players know what's new or updated.

**Comment by TheRealNin** [comment]
I totally agree! That would be awesome. I believe that is just an embedded web page. We could have it link to the wiki here on github.
