### ISSUE TITLE
Have front door kill clogs

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#43]
PASSED with a vote of 5/3/0 (y/n/a)

**Comment by jonsextra** [comment]
What about when the front doors open, you have them destroy all clogs/structures/player-built structures near the door?

**Comment by TheRealNin** [comment]
Is this still needed?

**Comment by jonsextra** [comment]
I think so. We still have some people blocking doors.

**Comment by DalinSeivewright** [comment]
sh_killclogs was added to the server tonight.  We can definitely still add this as part of siege if you want, but we can go with the command for now.

**Comment by jonsextra** [comment]
Screw it, that's good enough for me. Call it a workaround to a technical limitation and there's no need to amend the bill.
