### ISSUE TITLE
Make power node's with a CC damage notifications show up for ALL marines, not just the commander. Also make the warning lights/sounds occur at 90% health instead of 40% health (neither use armor. The alarm wouldn't go off if there's infestation, since that only removes armor.)

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#45]
PASSED with a vote of 7/1/0 (y/n/a)

**Comment by TheRealNin** [comment]
Seems like the notification system in NS2 is buggy as hell. Sometimes I can't get any notifications to show up at all. Maybe that's the real cause of our problems....

**Comment by cryticx** [comment]
This is implemented now, yes?

**Comment by TheRealNin** [comment]
No, I haven't got to fixing the notification system, but the power nodes now trigger at 90% health (including armor).

**Comment by TheRealNin** [comment]
The notification system was fixed in the latest update. Seems to have been UWE's fault for breaking it (something to do with the help menu)
