### ISSUE TITLE
Hives can heal through walls

### ISSUE THREAD

**Issue by TheRealNin** [TheRealNin/Siege-Collection#57]
it's also a massive amount of health

**Comment by jonsextra** [comment]
How about just make hives only heal in line of sight?

**Comment by TheRealNin** [comment]
Line of sight check is slow

**Comment by jonsextra** [comment]
But it'd prevent healing through walls. If you're already in the hive room the delay won't be a problem.

**Comment by TheRealNin** [comment]
By slow I mean make more work for the server. I think comparing the player's location to that of the hive would be safer.

**Comment by jonsextra** [comment]
Fair enough.
