### ISSUE TITLE
Add the Weapon Switch Improvements mod, and the Persistent Minimap Buildings mod to the Siege Collection.

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#74]
[https://steamcommunity.com/sharedfiles/filedetails/?id=1218273658&searchtext=](https://steamcommunity.com/sharedfiles/filedetails/?id=1218273658&searchtext=)
[https://steamcommunity.com/sharedfiles/filedetails/?id=1166463706&searchtext=](https://steamcommunity.com/sharedfiles/filedetails/?id=1166463706&searchtext=)

PASSED with a vote of 4/0/0 (y/n/a)

**Comment by TheRealNin** [comment]
Added the minimap buildings mod

**Comment by jonsextra** [comment]
Issue amended to "Add the Persistent Minimap Buildings mod to the Siege Collection" with a vote of 5/0/0 (y/n/a).
