### ISSUE TITLE
Implement Balance Changes to Make Games More Fair.

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#78]
a. Revert flamethrower's stats to pre 319
b. Reduce Onos' health buff to +25% vanilla. Increase the boneshield's width from ~140deg ~165 deg.
c. Give fade +15% hp. Reduce the effectiveness of fade's health regeneration by 50%.
d. Add the same jetpack fuel logic that Nin uses in his balance mod (weight reduces thrust and maneuverability instead of fuel use).
e. Repeal or drop Bill "Rebalance the HP and battle stuff by doing the following:" and revert all changes made by the bill.

PASSED with a vote of 6/2/0 (y/n/a)

**Comment by jonsextra** [comment]
Section b amended from "Reduce Onos' health buff to +25% vanilla. Increase the boneshield's width from ~115 deg ~135 deg" to "Reduce Onos' health buff to +25% vanilla. Increase the boneshield's width from ~140deg ~165 deg."

PASSED with a vote of 7/0/0 (y/n/a)

**Comment by TheRealNin** [comment]
> a. Revert flamethrower's stats to pre 319

Gonna need some thought on this one. It's not an easy task.

**Comment by jonsextra** [comment]
Issue D completed on technical end. Needs to be added to collection.
[https://steamcommunity.com/sharedfiles/filedetails/?id=1255326182](https://steamcommunity.com/sharedfiles/filedetails/?id=1255326182)

**Comment by TheRealNin** [comment]
Onos boneshield change is coming in next build

**Comment by jonsextra** [comment]
Section a. (Revert flamethrower's stats to pre 319) repealed with a vote of 5/0/0 (y/n/a).
