### ISSUE TITLE
Add Credits to the Server. Remove previous add credits issue (#2)

### ISSUE THREAD

**Issue by jonsextra** [TheRealNin/Siege-Collection#79]
Credits:
-Must be on a team at round's end in order to receive credits.
-Commanders, 3 credits per minute in the chair
-Credits calculated as: Score * 0.1 + Number of Kills + Number of assists * 0.5 + 1 credit per minute played
-Win multiplier: 1.2x
-One-time "New player" bonus of 50 Credits awarded on first recorded connection on the server. 
-Can't earn more than 300 credits per round
-Can only be exchanged for cosmetic items, or for items that do not otherwise effect gameplay. Exact items, and their respective costs, will be decided through general consensus, except in cases where consensus is not clearly achieved.

PASSED with a vote of 6/0/0 (y/n/a)

**Comment by TheRealNin** [comment]
This is done by Sog!
